### ISSUE TITLE
Battery percentage undefined or unknown

### ISSUE THREAD

**Issue by sonalder-darlene** [AsteroidOS/meta-sturgeon-hybris#19]
Hello,
I've install AsteroidOS on my Huawei Watch today and the battery level in the top menu (slide from home) is set to "undefined%" which is pretty anoying.
Is it normal that you can't get battery level from hardware ? And so I wont be able to ever seen it ?

**Comment by MagneFire** [comment]
Hi,

This is definitely not normal behavior. In fact it has been a long running issue that is yet to be properly resolved: https://github.com/AsteroidOS/asteroid/issues/94

Can you confirm that running the command `opkg configure` fixes the issue?

We actually have a patch that fixes this (https://github.com/AsteroidOS/meta-asteroid/pull/61) but it seems to introduce issues on mtk6580 based watches. So for the moment it has not been merged.

**Comment by sonalder-darlene** [comment]
What do you mean running opkg configure ?
I set the watch in adb usb mode plug in into a linux machine run that command and get a sweet "Command 'opkg' not found" tried with adb too.

I need a little more I'm a complete noob ^^'

**Comment by MagneFire** [comment]
From your Linux machine you should be able to use the command: `adb shell "opkg configure"`

Or typing: `adb shell` and enter the command `opkg configure` from there.

**Comment by sonalder-darlene** [comment]
It works after restarting the watch thanks :)

**Comment by d4nj1** [comment]
Hi,
I just had the same issue when initially flashing the latest nightly to Huawei watch (sturgeon).

After running `opkg configure` via `adb shell` and a reboot of the watch, the battery indicator shows a correct value again.

Here is the output generated by `opkg configure`:

```
/ # opkg configure
Configuring statefs.
Dumping loader "/usr/lib/statefs/libloader-default.so"
Dumping loader "/usr/lib/statefs/libloader-default.so"
Dumping loader "/usr/lib/statefs/libloader-inout.so"
Dumping loader "/usr/lib/statefs/libloader-inout.so"
Dumping loader "/usr/lib/statefs/libloader-qt5.so"
Dumping loader "/usr/lib/statefs/libloader-qt5.so"
Trying to dump default provider "/usr/lib/statefs/libprovider-power_udev.so"
DTOR:/usr/lib/statefs/libprovider-power_udev.so
provider-udev
Trying to dump qt5 provider "/usr/lib/statefs/libprovider-bluez.so"
Qt5 loader: loading /usr/lib/statefs/libprovider-bluez.so
provider-bluez
Trying to dump qt5 provider "/usr/lib/statefs/libprovider-connman.so"
Qt5 loader: loading /usr/lib/statefs/libprovider-connman.so
provider-connman
Trying to dump qt5 provider "/usr/lib/statefs/libprovider-mce.so"
Qt5 loader: loading /usr/lib/statefs/libprovider-mce.so
provider-mce
Trying to dump qt5 provider "/usr/lib/statefs/libprovider-profile.so"
Qt5 loader: loading /usr/lib/statefs/libprovider-profile.so
Segmentation fault
 * pkg_run_script: package "statefs" postinst script returned status 139.
 * opkg_configure: statefs.postinst returned 139.
```

Are there any further logs I can provide from my device for debugging?

**Comment by MagneFire** [comment]
Thanks for providing your output.
Fortunately, we have a solution almost ready (https://github.com/AsteroidOS/meta-asteroid/pull/83 which is a continuation of https://github.com/AsteroidOS/meta-asteroid/pull/61).

**Comment by MagneFire** [comment]
https://github.com/AsteroidOS/meta-asteroid/pull/83 has been merged. So it's solved :tada:
