### ISSUE TITLE
Always-on-Display clock uncentered

### ISSUE THREAD

**Issue by sonalder-darlene** [AsteroidOS/meta-sturgeon-hybris#20]
When the watch is in AoD mode the time is not properly center, and change the way it is not, sometimes on the right, sometimes on the bottom-left, sometimes on the top, etc...
This is really unconsistant and does not look nice at all.
I tried different watchfaces, sometimes it is and sometimes not... wtf?
When the watch wakes it goes to the center with wallpaper.

**Comment by MagneFire** [comment]
This is actually a feature :laughing: 

Most smartwatches (and recent phones) use OLED displays, these display age over time in that pixels `burn-in`. This makes pixels less responsive making it look as if a previous image is still vaguely visible.
A method that attempts to reduce this is to gradually move static elements around on the screen to reduce this issue.

To be fair though, AsteroidOS watchfaces have a more extreme method where watchfaces try to use the maximum available screen space, making this more obvious.

This forum post should give you a good idea of what burn-in looks like:
https://forum.xda-developers.com/attachments/1110161633_hdr-jpg.3932617/

**Comment by sonalder-darlene** [comment]
Ow sorry :')
